# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference

# Ronald Mulyono Abadi
# DBS Foundation Coding Camp 2023, Learning Path DevOps Engineer
# Kelas Expert, Belajar Membangun Arsitektur Microservices
# Submission Proyek Kedua: Proyek Deploy Aplikasi Karsa Jobs dengan Kubernetes
# File: ./circleci/config.yml

# Resources:
# - https://emmer.dev/blog/linting-dockerfiles-with-hadolint/

version: 2.1

executors:
  docker:
    docker:
      - image: docker:stable

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  lint-dockerfile-karsajobs:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    executor: docker
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "masuk ke folder karsajobs"
          command: cd karsajobs
      - run:
          name: "install dan jalankan hadolint"
          command: docker run --rm --interactive hadolint/hadolint < karsajobs/
  test-app:
    docker:
      - image: cimg/go:1.19.3
    steps:
      - checkout
      - run:      
          name: "lakukan test sesuai instruksi"
          command: cd karsajobs && go test -v -short --count=1 $(go list ./...)
  build-app-karsajobs:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "jalankan build_push_image_karsajobs.sh"
          command: sh /root/project/karsajobs/build_push_image_karsajobs.sh
  lint-dockerfile-karsajobs-ui:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "install dan jalankan hadolint"
          command: docker run --rm --interactive hadolint/hadolint < karsajobs-ui/
  build-app-karsajobs-ui:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "jalankan build_push_image_karsajobs_ui.sh"
          command: sh /root/project/karsajobs-ui/build_push_image_karsajobs_ui.sh

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  version: 2
  karsajobs-workflow:
    jobs:
      - lint-dockerfile-karsajobs
      - test-app:
          requires:
            - lint-dockerfile-karsajobs
      - build-app-karsajobs:
          requires:
            - test-app
  karsajobs-ui-workflow:
    jobs:
      - lint-dockerfile-karsajobs-ui
      - build-app-karsajobs-ui:
          requires:
            - lint-dockerfile-karsajobs-ui
